// Package core contains the canonical business logic for pokegents:
// state machine, session identity resolution, and shared types.
package core

// SessionState represents the state of an agent in the state machine.
type SessionState string

const (
	StateIdle       SessionState = "idle"
	StateBusy       SessionState = "busy"
	StateDone       SessionState = "done"
	StateNeedsInput SessionState = "needs_input"
	StateError      SessionState = "error"
)

// IsActive returns true if the agent is doing work or waiting for input.
func (s SessionState) IsActive() bool {
	return s == StateBusy || s == StateNeedsInput
}

// CanInterrupt returns true if a tool event (PreToolUse/PostToolUse) is
// allowed to set the state. Only busy and needs_input can be overwritten
// by tool events — done/error/idle require UserPromptSubmit to transition.
func (s SessionState) CanInterrupt() bool {
	return s == StateBusy || s == StateNeedsInput || s == ""
}

// HookEvent is the JSON payload from Claude Code lifecycle hooks.
// Received via HTTP POST from dashboard-notify.sh or via the hook input pipe.
type HookEvent struct {
	SessionID            string `json:"session_id"`
	HookEventName        string `json:"hook_event_name"`
	ToolName             string `json:"tool_name,omitempty"`
	ToolInput            any    `json:"tool_input,omitempty"`
	CWD                  string `json:"cwd"`
	LastAssistantMessage string `json:"last_assistant_message,omitempty"`
	NotificationType     string `json:"notification_type,omitempty"`
	TranscriptPath       string `json:"transcript_path,omitempty"`
	Prompt               string `json:"prompt,omitempty"`
}

// SessionIdentity holds the multiple IDs that identify an agent session.
// See CLAUDE.md "Session Identity" for why there are three IDs.
type SessionIdentity struct {
	// SessionID is Claude's conversation session ID (assigned by Claude, may change on resume).
	SessionID string
	// CCDSessionID is the stable unique ID generated by pokegent.sh (never changes, even for clones).
	CCDSessionID string
	// ProfileName is the profile this session was launched from.
	ProfileName string
	// TTY is the terminal device (e.g. /dev/ttys001).
	TTY string
	// ITermSessionID is the iTerm2 session UUID (stable across tab moves).
	ITermSessionID string
}

// StateTransitionResult is returned by ApplyEvent with the new state and metadata.
type StateTransitionResult struct {
	// NewState is the resulting state after the event.
	NewState SessionState
	// Skip is true if the event should be ignored (e.g. clone SessionStart on busy agent).
	Skip bool
	// Detail is the human-readable status detail.
	Detail string
	// Summary is the last assistant message (set on Stop).
	Summary string
	// BusySince is the timestamp when the agent became busy (set on UserPromptSubmit).
	BusySince string
	// ClearActions is true if recent_actions should be reset.
	ClearActions bool
	// ToolAction is the action string to append to recent_actions (if non-empty).
	ToolAction string
}
